# Docker Compose for quickly setting up a dev environment

wavecrack:
  container_name: wavecrack
  build: .
  ports:
    - 5000:5000
  links:
    - rabbit:rabbit
  volumes:
    # Bind the local folder to the /app/ folder in the container: the code
    # inside the container is synchronized in real-time
    - ".:/app/"

rabbit:
  container_name: the-rabbit
  image: rabbitmq:3-management
  hostname: rabbit
  ports:
    - 15672:15672
    - 5672
